# SPDX-FileCopyrightText: 2025 Menno van der Graaf <mennovandergraaf@hotmail.com>
# SPDX-License-Identifier: MIT

baseURL = "https://mercotui.com"
languageCode = "en-us"
title = "Mercotui"

[params]
nav_name = "home" # set home as default value
